---
services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_IMAGE_VERSION}
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/data:/data
...
