services:
  portainer:
    image: portainer/portainer-ce:2.21.1-alpine
    container_name: portainer
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/data:/data